### PR TITLE
webui: analytics module: show stored data per jobname in treemap

### PR DESCRIPTION
**Pull request by fbergkemper**
This PR introduces an analytics module into webui. The first feature of this new module
is a visualization of stored backup job data in a treemap.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General
- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR
- [x] `bareos-check-sources --since-merge` does not report any problems
- [x] `git status` should not report modifications in the source tree after building and testing

### CODE REVIEW

**Review by pstorz — CHANGES_REQUESTED** [review]
Good work.
- Do we want/need to have some docs about the new analytics module?
- The CHANGELOG.md commit is missing.

**Comment by fbergkemper** [comment]
> Good work.
> 
>     * Do we want/need to have some docs about the new analytics module?
> 

I don't think so, because the treemap is actually self-explanatory for users.

>     * The CHANGELOG.md commit is missing.

I'll add it after rebase and solving merge conflicts due to some pending PRs that will be merged first, I guess.

**Comment by fbergkemper** [comment]
After a second thought and look, we should add the new module here https://docs.bareos.org/IntroductionAndTutorial/BareosWebui.html#command-acl-requirements due to command.csv changes.

**Review by pstorz — APPROVED** [review]
Good work!

**Pull request merged**
