### PR TITLE
Bugfix for #1072 (Newer versions of Fedora use stricter code checking)

### PR DESCRIPTION
**Pull request by tuxmaster5000**
https://bugs.bareos.org/view.php?id=1072

### CODE REVIEW

**Comment by arogge** [comment]
Hi, thanks for the PR!
I'd really like to fix this problem. However, the line you propose the change for is probably better off by replacing it with strncpy().
The real issue is that our cmake config doesn't enable -Werror=format-security by default. We should fix that one!

**Comment by tuxmaster5000** [comment]
Exhange the patched.

**Comment by arogge** [comment]
Sorry, that one doesn't (yet) build on MacOS. The Xcode version we're using flags gettext strings as "not a string literal" which then triggers the format-security error.

**Comment by arogge** [comment]
I guess we will need to upgade the Xcode on our Mac build system before we can merge this.
This might take some time. Sorry.

**Comment by arogge** [comment]
I finally managed to get the MacOS builds working with a newer XCode version.
Not all tests have finished yet, but I think we will be able to merge this next week.

**Pull request merged**
