### PR TITLE
dird: deprecate client `Autoprune`, `JobRetention`, and `FileRetention`

### PR DESCRIPTION
**Pull request by alaaeddineelamri**
#### Description

This PR removes client `Autoprune`, `JobRetention`, and `FileRetention` from the client resource in the Director configuration.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Check backport line

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

### CODE REVIEW

**Review by sebsura — APPROVED** [review]

**Review by sebsura — CHANGES_REQUESTED** [review]
You updated the wrong file

**Review by sebsura — APPROVED** [review]

**Comment by Ropnuk** [comment]
Hello.
how to manage the duration of storage of backups and information about them?
In Dir->pool config? Or another way?

**Comment by sebsura** [comment]
What did you enter into bconsole and what do you expect it to print ?
And to your question: yes, you should use pool->autoprune for your autopruning needs.

**Comment by sebsura** [comment]
The best place to ask questions like these is in the user mailing list; see here https://www.bareos.com/community/join-in/ for details.

**Comment by Ropnuk** [comment]
In .conf file I see this:
Pool_conf
In bconsole I see this
Pool_bconsole
In bconsole there are no information about autoprune parameter.

**Comment by arogge** [comment]
`Pool->AutoPrune` is not `Client->AutoPrune` so this is totally unrelated to this PR.
In other news: `Pool->AutoPrune = yes` is the default, thus it is omitted on `show pool`.

**Comment by Ropnuk** [comment]
I understand.
Thank you for help

**Pull request merged**
