### PR TITLE
webui: add timeline chart by jobs

### PR DESCRIPTION
**Pull request by fbergkemper**
If multiple jobs are defined for one client, it makes sense to be able
to show the timeline based on jobs and not on clients.

Therefore, this PR introduces some changes to have a timeline chart
for clients in the clients module and a timeline chart for jobs in the
job module available.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR
- [x] `bareos-check-sources --since-merge` does not report any problems
- [x] `git status` should not report modifications in the source tree after building and testing

### CODE REVIEW

**Review by pstorz — CHANGES_REQUESTED** [review]
Looks very good and works as expected. I shortened the PR name a bit (and updated the CHANGELOG accordingly).

It would make sense to move the "client" based timeline on the right, and put the job based timeline on the left of the menu. I.e. the jobs based one is the default.

Good work"

**Comment by fbergkemper** [comment]
> Looks very good and works as expected. I shortened the PR name a bit (and updated the CHANGELOG accordingly).
> 
> It would make sense to move the "client" based timeline on the right, and put the job based timeline on the left of the menu. I.e. the jobs based one is the default.
> 
> Good work"

Thanks for the review.

**Comment by fbergkemper** [comment]
I've made the changes we discussed elsewhere yesterday, please have another look at the PR. Thank you.

**Review by pstorz — APPROVED** [review]
Looks good. Good work!

**Pull request merged**
