### PR TITLE
Add FreeBSD 13.3 and 14.0

### PR DESCRIPTION
**Pull request by arogge**
This PR adds the following platforms to matrix.yml:
- FreeBSD 13.3
- FreeBSD 14.0

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Required backport PRs have been created

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

### CODE REVIEW

**Review by sebsura — CHANGES_REQUESTED** [review]
Sadly i can only add notes to files that you actually touched, so i will write my notes here:

in freebsd/bareos-*.in we need to add a default value or we get an ugly warning:

```diff
modified   core/platforms/freebsd/bareos-fd.in
@@ -19,4 +19,5 @@ rcvar=bareosfd_enable
 command="@sbindir@/bareos-fd"
 
 load_rc_config $name
+: "${bareosfd_enable:=no}"
 run_rc_command "$1"
```
see https://docs.freebsd.org/en/articles/rc-scripting/ for reference.

I also have trouble connecting to the director on FreeBSD 14.0.  The director seems to crash whenever i try to connect with the console.   Ill see if I can get a traceback.

**Comment by sebsura** [comment]
It seems like the problem was just that installing `bareos-dir` did not also install `postgresql-server`

**Comment by sebsura** [comment]
Are you supposed to install `bareos-com.database-postgresql` seperately ? otherwise the installation instructions for `bareos-dir` dont work as `postgresql.sql` is missing.

**Comment by arogge** [comment]
> Are you supposed to install `bareos-com.database-postgresql` separately ? otherwise the installation instructions for `bareos-dir` dont work as `postgresql.sql` is missing.

I think so. IIRC when we dropped MySQL catalog support we decided not to remove the postgresql-package and move its files into the director package.

**Comment by arogge** [comment]
I pushed a fix for the rcscripts default values.

**Review by sebsura — APPROVED** [review]
Thanks for your work!  LGTM

**Pull request merged**
