### PR TITLE
Update spanish translation es_ES

### PR DESCRIPTION
**Pull request by EdwardNavarro**
Completed Spanish translation to 100% with some old corrected strings.

### CODE REVIEW

**Comment by fbergkemper** [comment]
Just to let you know, we changed the way how localization is done a while ago, see https://github.com/bareos/bareos/blob/master/webui/doc/README-TRANSLATION.md .

But I'm going to have a look if we can merge this nevertheless.

**Comment by EdwardNavarro** [comment]
Hi @fbergkemper, don't worry, I translated all strings directly in the POEditor project as described in the README. You can check and skip the PR. Thanks!

**Comment by fbergkemper** [comment]
Awesome, so going to skip this PR.

Cheers!

**Comment by fbergkemper** [comment]
Merged latest changes into master.

**Pull request closed without merging**
