### PR TITLE
vadp-dumper: fix multithreaded backup/restore issues

### PR DESCRIPTION
**Pull request by sebsura**
### Thank you for contributing to the Bareos Project!

This pr fixes some bugs of the vadp_dumper, mostly related to its multithreaded mode.  For example:
* fixed multithreaded writing trying to read from stdout instead of stdin
* fixed runtime value of sectors_per_call not being taken into account when allocating buffers
* fixed multiple data races related to memory reuse when using multithreaded mode

Additionally this PR adds support for the QueryAllocatedBlocks function in the following way:
Previously we backed up every block that was reported by vmware to have changed since some point
in time (or at all in case of full backups).  This list can contain blocks that were once changed but are now
not needed anymore which we previously backed up needlessly.  As such we now ask vmware to also give us a list
of all allocated (i.e. needed) blocks and backup only sectors that are both part of a allocated block and part of a
changed block.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Required backport PRs have been created

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

### CODE REVIEW

**Review by sduehr — CHANGES_REQUESTED** [review]
Thanks a lot, I'd like to suggest the following changes:

1. When passing `-s 0` to `bareos_vadp_dumper` it excessively consumes cpu and memory, so that value should be rejected.
2. Output like the following should only appear when `-v` was passed:
```
Making slot 3 bigger (4194304 -> 8388608)
Making slot 15 bigger (6291456 -> 8388608)
Changed len: 3471835136, Saved len: 3471835136
```

**Comment by sebsura** [comment]
The same will probably happen with `-s 1`, `-s 2`, ... (alltough `-s 0` is the worst).  What do you think a good minimum for the sectors_per_call value would be ? I imagine we could use the old value as minimum, i.e. 1024.

**Comment by sebsura** [comment]
I made it reject all numbers <= 0 as well as incorrect inputs (so `-s blabla` should now also not work)

**Comment by arogge** [comment]
pr-tool said the headline of commit "vadp-dumper: add support for VixDiskLib_QueryAllocatedBlocks()" is too long.

**Review by pstorz — APPROVED** [review]

**Review by sduehr — APPROVED** [review]
Thanks a lot, looks good now.

**Pull request merged**
