### PR TITLE
systemtests: devide webui selenium test into several individual tests

### PR DESCRIPTION
**Pull request by fbergkemper**

### CODE REVIEW

**Comment by joergsteffens** [comment]
Wouldn't it be preferable to configure ctest to run each pyunit/selenium tests separately without multiplying the code? This could be done similar to https://gist.github.com/dhandeo/4741027
See also https://github.com/bareos/bareos/blob/master/systemtests/CMakeLists.txt#L333.

**Comment by fbergkemper** [comment]
> Wouldn't it be preferable to configure ctest to run each pyunit/selenium tests separately without multiplying the code? This could be done similar to https://gist.github.com/dhandeo/4741027
> See also https://github.com/bareos/bareos/blob/master/systemtests/CMakeLists.txt#L333.

The intention here is to speed up testing by running a set of tests in parallel, each in its own environment.

`
$ ctest -j 10 -R webui
Test project /home/frank/Development/bareos-build
      Start 109: system:webui-admin-client-disabling
      Start 110: system:webui-admin-rerun-job
      Start 111: system:webui-admin-restore
      Start 112: system:webui-admin-run-custom-job
      Start 113: system:webui-admin-run-job
      Start 114: system:webui-readonly-client-disabling
      Start 115: system:webui-readonly-rerun-job
      Start 116: system:webui-readonly-restore
      Start 117: system:webui-readonly-run-custom-job
      Start 118: system:webui-readonly-run-job
 1/10 Test #112: system:webui-admin-run-custom-job ........   Passed   20.90 sec
 2/10 Test #115: system:webui-readonly-rerun-job ..........   Passed   20.92 sec
 3/10 Test #118: system:webui-readonly-run-job ............   Passed   21.20 sec
 4/10 Test #113: system:webui-admin-run-job ...............   Passed   22.18 sec
 5/10 Test #110: system:webui-admin-rerun-job .............   Passed   22.19 sec
 6/10 Test #117: system:webui-readonly-run-custom-job .....   Passed   22.21 sec
 7/10 Test #111: system:webui-admin-restore ...............   Passed   23.24 sec
 8/10 Test #116: system:webui-readonly-restore ............   Passed   23.40 sec
 9/10 Test #114: system:webui-readonly-client-disabling ...   Passed   24.24 sec
10/10 Test #109: system:webui-admin-client-disabling ......   Passed   26.07 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) =  26.08 sec
`

**Comment by pstorz** [comment]
329

**Comment by pstorz** [comment]
Is already merged as PR #329

**Pull request closed without merging**
