### PR TITLE
Bugfix: Director Python Plugin Baseclass replace obsolete bareos_dir_consts

### PR DESCRIPTION
**Pull request by benibr**
This PR should make the Director python plugin baseclass ready for bareos 20 with python3
It replaces the imports and other naming conventions of eventtypes, consts, etc. according to the doc

See also:
https://bugs.bareos.org/view.php?id=1332
https://support.bareos.com/index.php?module=HelpDesk&view=Detail&id=17x55442

OP#4884

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

### CODE REVIEW

**Comment by aussendorf** [comment]
Needs to be aligned with #PR877, both effect baseclass.

**Comment by benibr** [comment]
What exactly do you mean with "aligned"? The changes in the BaseClass in #877 differ from the ones I made. Eg. `bRCs[b"bRC_OK"]` vs. `bRC_OK` as returncodes.
Someone have to decide which way it should be merged.

**Review by sduehr — COMMENTED** [review]
Hi, as we've had conflicting contributions for BareosDirPluginBaseclass.py from this PR and PR #877, I've create the new PR #923 which also contains an adapte SD plugin baseclass and 
 a fix for the plugin_ctx is unset runtime error.

**Comment by sduehr** [comment]
Meanwhile PR #923 (which involves the changes from both this PR and PR #877) has been merged into master, so we can close this PR. Thanks for your contribution.

**Pull request closed without merging**
