### PR TITLE
Add PostgreSQL role switching

### PR DESCRIPTION
**Pull request by tuxmaster5000**
Add role switching for PostgreSQL.
See https://bugs.bareos.org/view.php?id=1456 for more.

##### General
- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR
- [x] `bareos-check-sources --since-merge` does not report any problems
- [x] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [x] Decision taken that a test is required (if not, then remove this paragraph)
- [x] The choice of the type of test (unit test or systemtest) is reasonable
- [x] Testname matches exactly what is being tested
- [x] On a fail, output of the test leads quickly to the origin of the fault

### CODE REVIEW

**Comment by bruno-at-bareos** [comment]
Thanks for the PR. Actually testing the build and systemtests in container make the test failed

**Comment by tuxmaster5000** [comment]
What is written in the log of the SQL server?

**Comment by bruno-at-bareos** [comment]
> What is written in the log of the SQL server?

I've increase the log level of postgresql in test 

```
2022-05-16 11:43:17.435 UTC [unknown] [unknown] [8329]LOG:  00000: connection received: host=[local]
2022-05-16 11:43:17.435 UTC [unknown] [unknown] [8329]LOCATION:  BackendInitialize, postmaster.c:4413
2022-05-16 11:43:17.436 UTC postgres root [8329]LOG:  00000: connection authorized: user=root database=postgres
2022-05-16 11:43:17.436 UTC postgres root [8329]LOCATION:  PerformAuthentication, postinit.c:292
2022-05-16 11:43:17.553 UTC postgres root [8329]LOG:  00000: disconnection: session time: 0:00:00.117 user=root database=postgres host=[local]
2022-05-16 11:43:17.553 UTC postgres root [8329]LOCATION:  log_disconnections, postgres.c:4767
```

While during a valid communication 
```
2022-05-16 11:43:15.027 UTC [unknown] [unknown] [8263]LOG:  00000: connection received: host=[local]
2022-05-16 11:43:15.027 UTC [unknown] [unknown] [8263]LOCATION:  BackendInitialize, postmaster.c:4413
2022-05-16 11:43:15.028 UTC backuptest root [8263]LOG:  00000: connection authorized: user=root database=backuptest application_name=psql
2022-05-16 11:43:15.028 UTC backuptest root [8263]LOCATION:  PerformAuthentication, postinit.c:292
2022-05-16 11:43:15.030 UTC backuptest root [8263]LOG:  00000: statement: SHOW server_version;
2022-05-16 11:43:15.030 UTC backuptest root [8263]LOCATION:  exec_simple_query, postgres.c:1044
2022-05-16 11:43:15.031 UTC backuptest root [8263]LOG:  00000: disconnection: session time: 0:00:00.003 user=root database=backuptest host=[local]
2022-05-16 11:43:15.031 UTC backuptest root [8263]LOCATION:  log_disconnections, postgres.c:4767
```

I'm attaching also the trace file of fd during that first backup
[py3plug-fd-postgres-fd.trace.txt](https://github.com/bareos/bareos/files/8700263/py3plug-fd-postgres-fd.trace.txt)

```diff
diff --git i/systemtests/tests/py2plug-fd-postgres/database/setup_local_db.sh.in w/systemtests/tests/py2plug-fd-postgres/database/setup_local_db.sh.in
index 49f196e03..d95b0f398 100755
--- i/systemtests/tests/py2plug-fd-postgres/database/setup_local_db.sh.in
+++ w/systemtests/tests/py2plug-fd-postgres/database/setup_local_db.sh.in
@@ -55,6 +55,13 @@ local_db_prepare_files() {
     echo "archive_mode = on"
     echo "archive_command = 'cp %p ../wal_archive'"
     echo "max_wal_senders = 10"
+    echo "log_connections = on"
+    echo "log_disconnections = on"
+    echo "log_min_messages = info"
+    echo "log_min_error_statement = info"
+    echo "log_error_verbosity = verbose"
+    echo "log_statement = 'all'"
+    echo "log_temp_files = 0"
   } >> data/postgresql.conf
 }

diff --git i/systemtests/tests/py2plug-fd-postgres/testrunner w/systemtests/tests/py2plug-fd-postgres/testrunner
index ab0651501..ad64113cf 100755
--- i/systemtests/tests/py2plug-fd-postgres/testrunner
+++ w/systemtests/tests/py2plug-fd-postgres/testrunner
@@ -50,7 +50,7 @@ cat <<END_OF_DATA >$tmp/bconcmds
 @$out /dev/null
 messages
 @$out $tmp/log1.out
-setdebug level=100 storage=File
+setdebug level=200 trace=1 all
 label volume=TestVolume001 storage=File pool=Full
 run job=$JobName yes
 status director
@@ -63,6 +63,8 @@ END_OF_DATA

 run_bareos "$@"

+exit
+
 # Now add data to the database and run an incremental job
 echo "INSERT INTO t (text, created_on) values ('test for INCR backup', current_timestamp)" | ${PSQL} ${DBNAME}
```

**Comment by tuxmaster5000** [comment]
Very strange, in this log's I don't see any errors.

**Comment by bruno-at-bareos** [comment]
> Very strange, in this log's I don't see any errors.
I will ask the experts :-) how to debug the internal python, it look like it is failing just after the plugin initialization, but before contacting for real the pg server.

**Comment by tuxmaster5000** [comment]
Without the full log's(database server, jenkins,test etc.) I can't do anything because on my systems, it works.

**Comment by bruno-at-bareos** [comment]
> Without the full log's(database server, jenkins,test etc.) I can't do anything because on my systems, it works.

You have a make test working ? here not.

**Comment by tuxmaster5000** [comment]
I test it in the live scenario, so I need the all log files to debug your test environment.

**Comment by tuxmaster5000** [comment]
I have try this, but no tests will start:
ctest -vvvv --output-on-failure -R fd-postgres 
will only log this:
PRETEST: checking configured hostname (foo.bar) ... OK
    Start 82: system:py2plug-fd-postgres
1/2 Test #82: system:py2plug-fd-postgres .......***Not Run (Disabled)   0.00 sec
    Start 83: system:py3plug-fd-postgres
2/2 Test #83: system:py3plug-fd-postgres .......***Not Run (Disabled)   0.00 sec
No tests were found!!!

**Comment by tuxmaster5000** [comment]
Very interesting both nodules are present.
In the console log of the cmake run I only see this:
```
disabling py2plug-fd-postgres, Python2 not supported for this plugin
-- Test: system:py2plug-fd-postgres => disabled ()
-- python module pyversion 3 pg8000 found
-- python module pyversion 3 dateutil found
-- Test: system:py3plug-fd-postgres => disabled ()
```
But no reason why py3plug-fd-postgres  is disabled.

**Comment by bruno-at-bareos** [comment]
> But no reason why py3plug-fd-postgres is disabled.

Maybe you don't have the python3 devel stack, but just the python2 (sorry, I'm just guessing) 
something similar to this list 
```
 python3-appdirs
 python3-base
 python3-devel
 python3-mysqlclient
 python3-ordered-set
 python3-packaging
 python3-pip
 python3-pyparsing
 python3-rpm
 python3-setuptools
 python3-six
 python3-dateutils
 python3-pg8000
```
Name varying a lot depending on distribution used.

**Comment by bruno-at-bareos** [comment]
> The python3 devel stuff is installed. Ah I found it: systemtests/tests/py2plug-fd-postgres/CMakeLists.txt Only allow Python up to 3.9, but the test system comes with python 3.10. So simple set AND (${Python3_VERSION_MINOR} LESS to 11 instant of 10 Now I can try to see if I see any errors on the code.

Not sure I understand, it seems we check that major version is 3, but also maybe it will be a good idea to rebase from master anyway.

**Comment by tuxmaster5000** [comment]
As far as I understood the test, it will only creates an test database for the test. But no director is set up.
The logs I only see that an connection to the director was failed. But I can't see, that an director  was set up.
Only the test database was created.

**Comment by bruno-at-bareos** [comment]
The bareos dir, fd, sd is setup during those part of the code
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

start_test
then
run_bareos "$@"

with your code the test is failing with a word "role" if you checkout master the test is working

**Comment by tuxmaster5000** [comment]
After an weekend debug session, it looks like as an general database problem.
The director can't start, because the socket path to the pgsql db is not set in the catalog config  file.
But when I set it manual, then the option "DB Socket" is complete ignored. The director will always only try "/var/run/postgresql/.s.PGSQL.5432" But correct will be "<builddir>systemtests/tests/py3plug-fd-postgres/tmp/.s.PGSQL.5432"

**Comment by tuxmaster5000** [comment]
Now it is very strange. Using an external db, then the director starts, but the test itself will also use this external db.
But as I understand the test config, it will try to setup an second database. But this will not happens. Or misunderstand I the test?

**Comment by tuxmaster5000** [comment]
Now I can repeat the problem with the test. But as far as work in the live system. I have rewritten it, so that it will work in both scenarios. (test and live system)

**Comment by bruno-at-bareos** [comment]
Nice addition, I wonder if we can't trick a bit more the test, to not only test without "role" needed but also when it is needed, 
like adding some parameter to the local tested PG ?
So code changes occur later, we will not silently loose or broke this functionality, What your thoughts on this ?

**Comment by tuxmaster5000** [comment]
For complete testing, 3 tests are needed. But I have not knowledge of writing cmake tests.
Here the "list" of needed tests
1. user with backup rights, without setting an role -> must pass
2. user without backup rights, without setting an role -> must fail
3. user without backup rights, with role switching -> must pass 
For all tests an clean test data base is needed.

**Comment by bruno-at-bareos** [comment]
Hi @tuxmaster5000 I completely agree with the 3 cases which would be the nice things to have.
The tests for this are not gtest but systemtest basically all written in bash ;-)

See the testrunner script and also the setup_local_database.sh.

**Comment by tuxmaster5000** [comment]
I seen an testrunner file, but how will it split into multiple test? I have never used the ctest framework before.

**Comment by bruno-at-bareos** [comment]
Hello @tuxmaster5000 (sorry for the delay, overloaded by other tasks).
I was thinking about hacking the database/setup_local_db.sh.in to create the needed role, then also modify etc/bareos/ configuration to add a test with the plugin and role 
I'm not sure if we want to drive the failing test in testrunner on first attempt then upgrade the right on the to be backuped pg cluster, and the retry should work. I guess this will depend of role management.

**Comment by tuxmaster5000** [comment]
As far as I understand the bareos test world I have created the 3 tests. But I don't see the way do build the "no role" test as an "experted fail" test like it can be done under python.

**Comment by tuxmaster5000** [comment]
No problem, in the meantime I use my one patched version internal. Thanks for your work.

**Comment by bruno-at-bareos** [comment]
Hello @tuxmaster5000 I didn't forget to work on this PR, just dedicated time was short, and maybe I discover something else that need to be fixed while drafting the test.
Can you tell me if the bareos-fd running user (usually root), is the "db_user" parameter used (if db_user is not set, then the connection is done by socket with the running user), and into your configuration you use the set role instruction to give that connecting user a "superuser" privileges ?

**Review by bruno-at-bareos — APPROVED** [review]
Final approval after renamed py2 to py3

**Pull request merged**
