### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by nibbl**

### CODE REVIEW

**Comment by pstorz** [comment]
Hello nibbl,

thank you very much for your PR.

It would be great if you could:

- create the PR against our master branch instead of bareos-20,
- reformat the commit message to contain a bit more information
- add your name to the AUTHORS file if you like

For details, please see the following documents.
https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits
https://docs.bareos.org/DeveloperGuide/generaldevel.html#patches

If something is unclear, please ask,

Best regards,

Philipp

**Review by nibbl — COMMENTED** [review]
Fix broken link after preparing changes on the https://bareos.org backend side

**Comment by pstorz** [comment]
Hello nibbl. 

It seems that something went wrong here, as now we have 14 commits that you want to merge instead of one. This is probalbly caused by the fact that you switched the reference branch but did not change your own branch to be based on the master branch.

Also, you did not add your name to the AUTHORS file.

Best regards,

Philipp

**Comment by nibbl** [comment]
Please, close this pull request, I will open new without other 14 commits

**Comment by pstorz** [comment]
As requested by nibbbl

**Pull request closed without merging**
