### PR TITLE
Added VirtualFull option to JobRun Form

### PR DESCRIPTION
**Pull request by tikoflano**
Added VirtualFull option for manual defined Jobs. In my case, sometimes you have a Full Job and some Incremental  ones and you just one to merge them into a new Virtual Full. From the UI it is really simple to do it if we add this option to the menu.

### CODE REVIEW

**Comment by fbergkemper** [comment]
Thanks for the PR, Alvaro.

**Comment by fbergkemper** [comment]
Looks good. Useful for many others, I think.

**Comment by fbergkemper** [comment]
Ok, here is just an idea if you would like to extend this a bit in a future PR. It would be great to have an additional form element (next pool) displayed but just in case you switched to a VirtualFull. The displayed form element (input select) should have the default Next Pool directive of the selected pool preselected but it should be possible to override it too. I think you get the idea.

Going to merge this one now.

Cheers,
Frank

**Comment by tikoflano** [comment]
Great! I'm working on the changes you proposes. They make sense to me.

**Comment by fbergkemper** [comment]
Nice, looking forward to it.

By the way, if you like, join our bareos-devel mailing list which is always a good place to discuss Bareos development related stuff.

https://groups.google.com/forum/#!forum/bareos-devel/join

**Pull request merged**
