### PR TITLE
Replace non-existent "latest" by 20 in Windows downloads links

### PR DESCRIPTION
**Pull request by jenzuslongus**
Replace non-existent "latest" by 20 in Windows downloads links

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR
- [x] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

### CODE REVIEW

**Comment by bruno-at-bareos** [comment]
Thanks you @jenzuslongus for your proposal. If you accept, we will drive you to improve the quality of the PR.

Here are my remark :

Description of the PR (and commit should be changed from)

- Fixed broken links to "latest" version of windows downloads by using version 20
+ Replace non-existent "latest" by 20 in Windows downloads links

Title of the PR should also reflect this changes.

**Comment by jenzuslongus** [comment]
@bruno-at-bareos Thank you for your proposals. I hope that I corrected the comment and title accordingly. If not, please let me know what else is needed.

**Review by bruno-at-bareos — APPROVED** [review]
Thanks everything is ok.

**Comment by bruno-at-bareos** [comment]
@pstorz merge is normally ready for approval.

**Pull request merged**
