### PR TITLE
docs: corrected some wording

### PR DESCRIPTION
**Pull request by Zephyr82**
#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [ ] PR name is meaningful
- [ ] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [ ] Commit descriptions are understandable and well formatted

##### Source code quality

- [ ] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [ ] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [ ] The decision towards a systemtest is reasonable compared to a unittest
- [ ] Testname matches exactly what is being tested
- [ ] Output of the test leads quickly to the origin of the fault

### CODE REVIEW

**Comment by fbergkemper** [comment]
Thanks for your contribution. Please change the commit description/subject to "docs: corrected some wording", afterwards the PR can be approved and merged.

**Comment by Zephyr82** [comment]
Thank you very much for the hint. I changed the subject of the pull request. At least I think I did, didn't I?

**Comment by fbergkemper** [comment]
I did the PR subject change. ;) Please do the same for 
commit bbef4b96515fd7e3f77ebd010d4ac435707cc96c message, thank you.

**Comment by fbergkemper** [comment]
I adjusted the commit message as requested in another PR, so I'm going to close this PR.

See: PR#806 - https://github.com/bareos/bareos/pull/806

**Pull request closed without merging**
