### PR TITLE
core: Fix compile errors on GCC 14

### PR DESCRIPTION
**Pull request by csfore**
Starting in GCC 14, it will no longer include `<algorithm>` by default, resulting in compile errors for various projects.

https://gcc.gnu.org/gcc-14/porting_to.html

Errors:
```
core/src/cats/sql_get.cc:1309:42: error: cannot convert 'std::vector<std::__cxx11::basic_string<char> >::iterator' to `const char*'

  1309 | jobids.erase(std::remove(jobids.begin(), jobids.end(),
    remove_jobid),

core/src/stored/append.cc:78:3: error: `for_each' was not declared in this scope

 78 |   for_each(attributes_.begin(), attributes_.end(),

core/src/dird/ua_prune.cc:897:27: error: `remove_if' is not a member of `std'; did you mean `remove_cv'?

  897 |     prune_list.erase(std::remove_if(prune_list.begin(),
     prune_list.end(),
```

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- ~Your name is present in the AUTHORS file (optional)~

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Check backport line
- [x] Required backport PRs have been created

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

### CODE REVIEW

**Comment by arogge** [comment]
Thank you for taking the time to fix this. I'll also backport this change into Bareos 23. Do you also need this in older versions (i.e. 22 and 21)?

**Review by arogge — APPROVED** [review]

**Comment by csfore** [comment]
Happy to help! If it's not too much trouble, backporting to 22 would be nice, thank you!

**Review by arogge — CHANGES_REQUESTED** [review]
I guess you're bulding without gtest installed. There is another missing `#include <algorithm>` in core/src/tests/addresses_and_ports_config.cc
Would you fix that aswell or should I do it?

**Comment by csfore** [comment]
Sorry for the delayed response! I'll be happy to do it if you haven't already.

**Comment by arogge** [comment]
Sure, go on. I'll happily backport it afterwards :)

**Review by arogge — APPROVED** [review]

**Pull request merged**
