### PR TITLE
docs: rename Autochanger chapter to include Tape drive support

### PR DESCRIPTION
**Pull request by norstbox**
"Tapespeed and blocksizes" section is not specific only to autochangers.
Proposed changes: introduce new "Performance Tuning" chapter and move "Tapespeed and blocksizes" section to it.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [X] Commit descriptions are understandable and well formatted

##### Source code quality

- [X] Source code changes are understandable
- [X] Required documentation changes are present and part of the PR
- [X] `bareos-check-sources --since-merge` does not report any problems
- [X] `git status` should not report modifications in the source tree after building and testing

### CODE REVIEW

**Comment by norstbox** [comment]
Related to https://bugs.bareos.org/view.php?id=1397

**Comment by bruno-at-bareos** [comment]
Hello @norstbox thanks a lot for the proposal. 
May I ask you, why you created a new chapter when this is what you complain about in the bug report.
Actually it make more sense to put directly Tapespeed and blocksizes on first level, instead hidden it again below a chapter which is a too wide subject. Aka Performance and tuning is all about all part of the whole configuration.

Would you mind to adjust accordly the PR ?

**Comment by norstbox** [comment]
> May I ask you, why you created a new chapter when this is what you complain about in the bug report.

I created a new chapter in advance solely for the better structuring. So, performance related topics maybe created and/or moved to this chapter in the future.

My concern was only about misleading chapter name, not nesting level. Actually, since I have no interest in autochangers, "Autochanger Support" chapter was skipped by me while viewing the documentation. I filed a bug after stumbled upon the "Tapespeed and blocksizes" section later, from search results.

>Actually it make more sense to put directly Tapespeed and blocksizes on first level, instead hidden it again below a chapter which is a too wide subject.

I will adjust PR accordingly if you still see "first level" approach as better suited after explanation above.

**Comment by bruno-at-bareos** [comment]
Hello, the problem with a chapter named "Performance & Tuning" is too vague, as then readers will expect to find all tips and tricks inside this chapter, when it clearly not the case.

From what you said, then the simple changes would have been to rename autochanger chapter to "autochanger & tape drive",
as there's also the cleaning section into that one.

**Comment by norstbox** [comment]
> From what you said, then the simple changes would have been to rename autochanger chapter to "autochanger & tape drive

Yes make sense. PR has been corrected accordingly.

**Comment by bruno-at-bareos** [comment]
Thanks, 
The last step now to make the PR almost perfect, would be to merge the previous commit (or just restart from master), so in commit history we will see only the title change ?

I've already adapted the PR subject (can be also use for the commit), we are in a process to revisit commit message and pr title to be more affirmative with clear statement about the changes (so "for better clarity" is too vague).

Regards

**Comment by norstbox** [comment]
> The last step now to make the PR almost perfect, would be to merge the previous commit (or just restart from master), so in commit history we will see only the title change ?

Done as I understand, please check.

Just for the curious, why you don't want to use build-in github [Squash the commits into one commit](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request) functionality?

**Review by bruno-at-bareos — APPROVED** [review]
Reviewed ok
Can be merged without adding a changelog line

**Comment by bruno-at-bareos** [comment]
Review done, merge will occur soon.

> Just for the curious, why you don't want to use build-in github [Squash the commits into one commit](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request) functionality?
I will forward this to our team, actually with have often still merge conflict to be resolved in CHANGELOG, a hook will soon resolve those, then afterwards....

**Pull request merged**
