### PR TITLE
Format joblogs to show direct link to queued jobs

### PR DESCRIPTION
**Pull request by tikoflano**
Add an special case for formatting the joblog message. It takes the messages in the form JobId=xxx and turns it to a link to that job. Usefull for those jobs that queue other jobs.

### CODE REVIEW

**Comment by fbergkemper** [comment]
Thank for the PR, Alvaro.

But please do us a favour and do your PR against the master branch, which is our development branch.

Release branches usually only receive bug fixes and sometimes other backports from master if we think it is really necessary.

Have a look at https://github.com/bareos/bareos/blob/a17c429a3358ea22fe01f32ffb2a232181bd1b1b/webui/public/js/bootstrap-table-formatter.js#L490 . This is where your suggested change now belongs, the code slightly changed since the release of 19.2.

It also would be great if you change the logic slightly in the formatter function in that way that multiple matches are possible and all substitutions are applied on a single log message. E.g. a message with an Error and a JobId should have the highlighting and the link applied.

If you have any questions don't hasitate to ask.

Cheers,
Frank

**Comment by tikoflano** [comment]
Hi Frank,
I would like to keep contributing to the Bareos webui project. So far I had made small changes editing the files directly from github, but for bigger changes I would like to be able to build the project from the source. 

I have set up a dev environment on Docker but I couldn't find any documentation on how to build the project. I have installed `cmake` but I'm not sure how to use it. Where can I find some documentation?

**Comment by fbergkemper** [comment]
Great! Have a look at the "Build and Test Bareos" chapter, see https://docs.bareos.org/master/DeveloperGuide/BuildAndTestBareos.html .

If you're stuck or need further information let me know, I'm happy to help you out. If you think the Developer Guide is missing something, please let us know, so we can improve it.

Cheers,
Frank

**Comment by fbergkemper** [comment]
Regarding WebUI development with self-compiled Bareos daemons, the fastest and easiest way without having to explain too much now is probably using "regress" to get you started.

1. After git cloning the repository, change into the regress folder.

`cd regress`

2. Copy the prototype.conf to config as described in the the README file in the regress folder. 

`cp prototype.conf config`

3. Usually it's enough to just adapt the DBTYPE in the created config file. I would recommend using SQLite for development purposes for now.

`DBTYPE="sqlite3"`

4. Do a "make setup" in the regress folder to build and setup everything. It will let you know which dependencies are missing, you might need to install some additional libraries and header files to be able to build the daemons properly. If you have struggle at this point let me know which distro you are using and I will try to help you out which additional packages are required for a successful build.

`make setup`

5. Start the Bareos daemons from within the regress folder after you build successfully.

`bin/bareos start`

6. Start the PHP Development Server from within the regress folder.

`php -S 0.0.0.0:9100 -t ../webui/public/`

7. The UI is now available at http://<IP>:9100/ 

user: admin
pass: admin

Additional notes:

- Changes to the webui code are immediately available as the webui source (bareos/webui/*) is used in this setup (except changes to *.in files which are proccessed and require a new build).
- Bareos configuration files of this setup are located in regress/bin/* .
- A bconsole can be called by bin/bconsole from within the regress folder.
- You can restart the daemons after doing config changes in regress/bin/* by bin/bareos restart from within the regress folder.
- You can stop the daemons by bin/bareos stop from within the regress folder.


I hope these steps and notes will get you started without hassle. If not let me know and will try to give you further directions.

Cheers,
Frank

**Comment by tikoflano** [comment]
Is there a way to build just the webui php files?

I have my bareos webui running on a container with URL bareos.example.com and I have another container running with URL dev.bareos.example.com. Both shares the same director, so I can use the  released webui or my own dev-webui. This way I don't have to compile all the extra stuff.

Also, is this the proper comunication channel for this conversation? Or should I write you  via mail or other way?

**Comment by fbergkemper** [comment]
> 
> 
> Is there a way to build just the webui php files?
> 
> I have my bareos webui running on a container with URL bareos.example.com and I have another container running with URL dev.bareos.example.com. Both shares the same director, so I can use the released webui or my own dev-webui. This way I don't have to compile all the extra stuff.
>

Considering the availabilty of PHP in your container, a rather hackish approach could be something like the following basic steps in your dev.bareos.example.com container.

git clone git@github.com:bareos/bareos.git

cd bareos/webui/

cp module/Application/view/layout/login.phtml.in module/Application/view/layout/login.phtml
cp module/Application/view/layout/layout.phtml.in module/Application/view/layout/layout.phtml

sudo mkdir /etc/bareos-webui
sudo cp install/configuration.ini.in /etc/bareos-webui/configuration.ini
sudo cp install/directors.ini.in /etc/bareos-webui/directors.ini

cp config/autoload/global.php.in config/autoload/global.php

In config/autoload/global.php change the following from ...

if(strlen(getenv('BAREOS_WEBUI_CONFDIR')) > 0) {
   $directors_ini = getenv('BAREOS_WEBUI_CONFDIR')."/directors.ini";
   $configuration_ini = getenv('BAREOS_WEBUI_CONFDIR')."/configuration.ini";
} else {
   $directors_ini = "@WEBUICONFDIR@/directors.ini";
   $configuration_ini = "@WEBUICONFDIR@/configuration.ini";
}

... to ...

if(strlen(getenv('BAREOS_WEBUI_CONFDIR')) > 0) {
   $directors_ini = getenv('BAREOS_WEBUI_CONFDIR')."/directors.ini";
   $configuration_ini = getenv('BAREOS_WEBUI_CONFDIR')."/configuration.ini";
} else {
   $directors_ini = "/etc/bareos-webui/directors.ini";
   $configuration_ini = "/etc/bareos-webui/configuration.ini";
}

... and ...

$arr[key($directors)]['port'] = @dirport@;

... to ...

$arr[key($directors)]['port'] = 9101;


cp version.php.in version.php

In version.php replace the following ...

$bareos_full_version = "@BAREOS_FULL_VERSION@";

... with ...

$bareos_full_version = "19.2.7";



Adjust /etc/bareos-webui/directors.ini to be able to connect to the DIRD you want to.

Start the PHP development server.

php -S 0.0.0.0:9100 -t ./public/


> Also, is this the proper comunication channel for this conversation? Or should I write you via mail or other way?

To keep PR discussions clean from this off-topic conversation, I would like to suggest to continue on the bareos-devel mailing list or you just drop me a mail if you like that more for further assistance.

My mail address can be found here e.g. `git log -p 2b897a64ed2a3983893f879ee064e986e6ae9d82`

Cheers,
Frank

**Comment by tikoflano** [comment]
This has been replaced with [this PR](https://github.com/bareos/bareos/pull/525)

**Pull request closed without merging**
