### PR TITLE
Update cs_CZ.po

### PR DESCRIPTION
**Pull request by p-bo**

### CODE REVIEW

**Comment by fbergkemper** [comment]
Thanks for your contribution.

**Comment by p-bo** [comment]
Would it be possible to open Czech (and import there) translation in translation project on Poeditor.com please?

**Comment by p-bo** [comment]
It is available - thanks :)
Corrected fuzzy translations and few bits too. Now there on poeditor.com are:
webui/module/Application/language/cs_CZ.po
webui/public/js/locale/cs_CZ/LC_MESSAGES/cs_CZ.po
would it be possible to add to poeditor.com also content from https://github.com/bareos/bareos/tree/master/core/po
to translate please?
Thanks :)

**Comment by fbergkemper** [comment]
Great. The localization branch is based on master. Changes made by contributors will be merged into master branch soon.

Currently we just work with one localization branch and changes are re-based, merged or cheery-picked between branches. Meaning, by now it should not be necessary to make another branch available to edit via poeditor.com. This may changes in future, if the current workflow is no longer practical.

Regards
Frank

**Comment by p-bo** [comment]
There may be misunderstanding - strings are in three places in source code - see above. For Czech there is covered two of them for web interface (288 strings total), but in template for core in third location, /core/po/bareos.pot, there are additional about 3000 strings to translate, which would be nice to expose on poeditor.com.
Is it clear now please?

**Pull request merged**
