### PR TITLE
- Polish translation, 50%

### PR DESCRIPTION
**Pull request by spidero**
Polish translation, 50%, work in progress

### CODE REVIEW

**Comment by spidero** [comment]
work in progress

**Comment by fbergkemper** [comment]
If this is going to be merged, a few preparations are required afterwards so translations via https://poeditor.com/join/project/ELnLNbvQJb are possible in future.

**Comment by jarekherisz** [comment]
Who can create polish translations project on https://poeditor.com/join/project/ELnLNbvQJb ?

**Comment by fbergkemper** [comment]
The PR is on the backlog and going to be handled during the next 2 weeks. I'll let you know when preparations are done.

> @fbergkemper
> Who can create polish translations project on https://poeditor.com/join/project/ELnLNbvQJb ?

The PR is on the backlog and going to be handled during the next 2 weeks. I'll let you know when preparations are done and polish has been added to the project at https://poeditor.com/join/project/ELnLNbvQJb.

**Comment by fbergkemper** [comment]
Polish has been integrated and also been added to https://poeditor.com/join/project/ELnLNbvQJb

**Pull request merged**
