### PR TITLE
Dev/joergs/bareos 18.2/univention

### PR DESCRIPTION
**Pull request by joergsteffens**
The univention-bareos package provides extra functionality on Univention UCS systems.
While this package have been build in bareos-17.2, it is not build on bareos-18.2, due to the switch from automake to cmake.
This patch enables the build again.
As I'm not familiar with the cmake environment, please verify, if I've chosen the correct approach.

### CODE REVIEW

**Comment by franku** [comment]
merged into bareos-18.2 with commit c5e3d4dc23165191b572ccc617f127165f7edc5a

**Comment by joergsteffens** [comment]
c5e3d4d is only one of two commits in this PR. The bugfix from e4c8c766997293352ffa2e02824c1b98a38982c9 is not yet merged.

**Comment by franku** [comment]
merged into bareos-18.2: 

- da72d6eda8e82eccd676744fb5f2781b80e269cb (bugfix from e4c8c766997293352ffa2e02824c1b98a38982c9) and 

-  da1179c86720364c4c3a20e3166338086d68617f (corrected merge error)

**Comment by franku** [comment]
merged into master:
c5e3d4dc2 -> 6b15392dc
da72d6eda -> 1dd648158

**Pull request closed without merging**
