### PR TITLE
webui: quote strings with slashes in media details view

### PR DESCRIPTION
**Pull request by gnieark**
Hello,
Using the french po file translation. Once computed by PHP engine, the given javascript file contains:

    html.push('<th>Nombre d'écritures sur le volume</th>');

Paf the apostrophe!

Thanks!

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [ ] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [ ] Variable and function names are meaningful
- [ ] Code comments are correct (logically and spelling)
- [ ] Required documentation changes are present and part of the PR
- [ ] `bareos-check-sources --since-merge` does not report any problems
- [ ] `git status` should not report modifications in the source tree after building and testing

### CODE REVIEW

**Comment by fbergkemper** [comment]
I've changed the pull request subject slightly to be more precise on what your proposed change does.
Also I've added our pull request template text to your first comment for the review process.

Can you please squash those two commits ( https://github.com/bareos/bareos/pull/887/commits/7d34ccfcb71336b4492e423a2ffecc739cd8371d & https://github.com/bareos/bareos/pull/887/commits/cc3bde80b2ebf26e587438b360f18071d493a8b6) into a single one and change the commit title to "webui: quote strings with slashes in media details view" ?

Thanks in advance.

**Comment by gnieark** [comment]
@fbergkemper Hello,
No problem to squash the two commits and change the title.

I discovered the same mistake could happen on others modules. By sample, the file webui/module/pool/view/pool/pool/details.phtml got some lines like this one
html.push('<th><?php echo $this->translate("First written"); ?></th>');

Do you want i check all the concerned parts and make a more fully fix?

**Comment by fbergkemper** [comment]
> 
> 
> @fbergkemper Hello,
> No problem to squash the two commits and change the title.
> 
> I discovered the same mistake could happen on others modules. By sample, the file webui/module/pool/view/pool/pool/details.phtml got some lines like this one
> html.push('translate("First written"); ?>');
> 
> Do you want i check all the concerned parts and make a more fully fix?

If you like move on, it would be awesome, to be honest.
Please do a separate commit for each module/view.

We should change the PR subject to sth. like quote strings with slashes afterwards when you are finished.

Thanks in advance

**Comment by gnieark** [comment]
It's ok
the commits are squashed  and it's renamed.

I'll do separates PR for the others modules

**Comment by fbergkemper** [comment]
> 
> 
> It's ok
> the commits are squashed and it's renamed.
> 

Please reword the commit title from "WEBUI - webui: quote strings with slashes in media details view" to "webui: quote strings with slashes in media details view".

We usually use the following format for commit titles.

<component>: <short summary> 

<long description>

See: https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits

> I'll do separates PR for the others modules

Ok, great!

**Comment by gnieark** [comment]
> Please reword the commit title from "WEBUI - webui: quote strings with slashes in media details view" to "webui: quote strings with slashes in media details view".

Oops
It's done

**Review by fbergkemper — APPROVED** [review]
Looks good!

**Pull request merged**
