### PR TITLE
sending all related Plugin Options to FD

### PR DESCRIPTION
**Pull request by benibr**
This is a WIP fix for https://bugs.bareos.org/view.php?id=1106

### CODE REVIEW

**Comment by franku** [comment]
Thank you for your contribution. We are going to discuss your PR in our next developer meeting.

**Comment by franku** [comment]
Will follow up next week after vacation of an appropriate reviewer. Thanks for waiting.

**Comment by benibr** [comment]
Thanks for the review and the feedback!
Handling the information inside the plugin of course is another story but it could be possible to merge the information on director side and sending them all at once.
Should I try this out or is anything else expected from me to get this upstream?

**Comment by franku** [comment]
We are running this on our test systems now. There should not be anything more for you to do.

**Comment by sduehr** [comment]
Thanks a lot for your contribution.
We will probable change BareosFdPluginBaseclass.py later, to make it possible to override plugin options defined in the FileSet by using FD Plugin Options in the Job resource.
Created https://bugs.bareos.org/view.php?id=1110

**Pull request merged**
