### PR TITLE
docs: corrected some wording

### PR DESCRIPTION
**Pull request by Zephyr82**
#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted

### CODE REVIEW

**Comment by fbergkemper** [comment]
Please do the PR with your changes on the master branch first. We are going to decide afterwards if a backport to the bareos-20 branch is required. Thank you.

**Comment by Zephyr82** [comment]
Oh noooz, I'm doin' it all wrong /o\ ;O)

**Comment by fbergkemper** [comment]
> 
> 
> Oh noooz, I'm doin' it all wrong /o\ ;O)

No worries, practice makes perfect.

Git Workflow: https://docs.bareos.org/master/DeveloperGuide/gitworkflow.html

**Comment by fbergkemper** [comment]
This is a backport to bareos-20 of https://github.com/bareos/bareos/pull/806

**Review by fbergkemper — APPROVED** [review]

**Comment by fbergkemper** [comment]
Zephyr82: No further action from you required, we handle this. Thanks again for the contribution.

**Review by pstorz — APPROVED** [review]

**Pull request merged**
