### PR TITLE
VMware plugin: fix check_mac_address() for vm.config not present

### PR DESCRIPTION
**Pull request by swenske**
Avoid errors with VM without a config attribute (eg: a VM being cloned)

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [ ] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [ ] Commit descriptions are understandable and well formatted
- [ ] Required backport PRs have been created
- [ ] Correct milestone is set

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)

### CODE REVIEW

**Comment by swenske** [comment]
When the vmware plugin recreates a VM it checks all MAC addresses to avoid a conflict.
If a cloning (or maybe also migration) task is in progress, the destination VM does not have a config yet and the following error occurs:
```
2024-11-20 15:53:18.874 | DEBUG | bareos-fd-vmware:check_mac_address:3131 - !!! vm: 'vim.VirtualMachine:vm-233350'
2024-11-20 15:53:18.878 | DEBUG | bareos-fd-vmware:check_mac_address:3132 - !!! vm.config: None
bareos-disk-sd-int-fr2.storage.xxxx.xxxx.xx (150): include/python_plugins_common.inc:125-30 bareosfd: Traceback (most recent call last):
 File "/usr/lib/bareos/plugins/BareosFdWrapper.py", line 59, in handle_plugin_event
 return bareos_fd_plugin_object.handle_plugin_event(event)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 1076, in handle_plugin_event
 return self.start_restore_job()
 ^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 618, in start_restore_job
 return self.vadp.prepare_vm_restore()
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 1549, in prepare_vm_restore
 if not self.create_vm():
 ^^^^^^^^^^^^^^^
 File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 1883, in create_vm
 self.check_mac_address(config_info)
 File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 3133, in check_mac_address
 for dev in vm.config.hardware.device:
 ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'hardware'
```

**Comment by bruno-at-bareos** [comment]
Our CI report the following issues
```
[2024-12-09T12:49:58.060Z]  ✗  Commit checks failed:

[2024-12-09T12:49:58.060Z] 	1374799f3 fix: AttributeError: 'NoneType' object has no attribute 'hardware': headline too long (66 > 60)

[2024-12-09T12:49:58.060Z] 	1374799f3 fix: AttributeError: 'NoneType' object has no attribute 'hardware': body contains line longer 72 chars

[2024-12-09T12:49:58.061Z]  ✗  bareos-check-sources --since=12624050ca36025cac38db74fcbd84907983191a reported:

[2024-12-09T12:49:58.061Z] 	Plugin 'python black' would modify core/src/plugins/filed/python/vmware/bareos-fd-vmware.py'
```

Would be nice to have them fixed before the start of the review.
You can always run them from your PR (see in devtools/)

**Review by sduehr — CHANGES_REQUESTED** [review]
Thanks for you contribution, I just requested a small change to make the code better readable.

You are right, vm.config may not be present, the [API docs](https://vdc-download.vmware.com/vmwb-repository/dcr-public/1ef6c336-7bef-477d-b9bb-caa1767d7e30/82521f49-9d9a-42b7-b19b-9e6cd9b30db1/vim.VirtualMachine.html#field_detail) also explains that.

**Comment by sduehr** [comment]
I changed the title so that it is usable as a CHANGELOG entry.

The commit checks still fail, the headline of a commit message must not be longer than 60 characters, and lines in the body of the commit message must not be longer than 72 characters.

Could you please rebase your git branch and cleanup (squash) the commits? I'd suggest to use
`VMware plugin: fix check_mac_address()`
as the commit message headline.

See also  https://docs.bareos.org/DeveloperGuide/gitworkflow.html
Note that a separate commit for the CHANGELOG entry is no longer necessary, this is automatically taken from the PR title now, we still have to remove that from the documentation.

And if you want, please add you name to the AUTHORS file.

**Comment by swenske** [comment]
I got a little confused with git, I hope I did it correctly.

**Pull request closed without merging**
