### PR TITLE
core cats: Add `IF EXISTS` in drop table statements

### PR DESCRIPTION
**Pull request by bruno-at-bareos**
- Using if exists avoid return of fatal error from database
  Allow the use of parameter ExitOnFatal = true on normal workflow

Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>

#### Please check

- [X] Short description and the purpose of this PR is present _above this paragraph_
- [X] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR
- [x] `bareos-check-sources --since-merge` does not report any problems
- [x] `git status` should not report modifications in the source tree after building and testing

### CODE REVIEW

**Comment by bruno-at-bareos** [comment]
Question: shall we add a systemtest for checking parameter ExitOnFatal = yes ?

**Comment by pstorz** [comment]
> Question: shall we add a systemtest for checking parameter ExitOnFatal = yes ?
What should be this test for? The ExitOnFatal works as we see in the bug report :)

**Comment by bruno-at-bareos** [comment]
> > Question: shall we add a systemtest for checking parameter ExitOnFatal = yes ?
> > What should be this test for? The ExitOnFatal works as we see in the bug report :)

The test would have to run bareos-dir with ExitOnFatal = on to check we don't introduce a new error afterwards. But this is certainly too nitpicky

**Review by pstorz — CHANGES_REQUESTED** [review]
Good work, makes sense. I have the following remarks:

* The info which bug is fixed should not be part of the PR title but from the commit that fixes the bug:
  See: 
  https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commit-message-guideline

* Also, a CHANGELOG.md line is missing. There the fixed bug also should be referenced.

**Comment by bruno-at-bareos** [comment]
Everything should be no fixed

**Review by pstorz — CHANGES_REQUESTED** [review]
The commit should contain a line 

`Fixes #1409: DB error on restore with ExitOnFatal=true`

This will automatically link the commit with the mantis bug.
Other than this everything is fine!

**Review by pstorz — APPROVED** [review]
Good work

**Pull request merged**
