### PR TITLE
Fix warning about missing delcandidates table in director

### PR DESCRIPTION
**Pull request by arogge**
**Backport of PR #1721 to bareos-23**

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### Source code quality (if there were changes to the original PR)
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

#### Backport quality
- [x] Original PR #1721 is merged
- [x] All functional differences to the original PR are documented above

### CODE REVIEW

**Review by sebsura — CHANGES_REQUESTED** [review]
You backported https://github.com/bareos/bareos/commit/23db06e714846aa277b0ca98e513a2550a1580a1 but the right commit is d2ff7898b9c26e228e9cbdc367badb00d4a18b2e .

Did you backport an old version ?

**Review by sebsura — APPROVED** [review]
Looks like the same to me!

**Comment by arogge** [comment]
@smarsching just in case you weren't aware, this PR is the backport of your changes (and should be merged soon now)

**Comment by smarsching** [comment]
@arogge I wasn’t aware, so thank you for letting me know.

**Pull request merged**
