### PR TITLE
contrib: add packaging for the contrib subproject

### PR DESCRIPTION
**Pull request by joergsteffens**
Add packages
       * bareos-contrib-director-python-plugins.install
       * bareos-contrib-filedaemon-python-plugins.install
       * bareos-contrib-tools
    
Renamed triggerjob to bareos-triggerjob to indicate, that it belongs to Bareos.

Removed support for RHEL4 from SPEC file. It is no longer used.

OP#4820

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General

- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR
- [x] `check-sources --since-merge` does not report any problems
- [x] `git status` should not report modifications in the source tree after building and testing

##### Tests

- [x] Decision taken that a system- or unittest is required (if not, then remove this paragraph)
- [x] The decision towards a systemtest is reasonable compared to a unittest
- [x] Testname matches exactly what is being tested
- [x] Output of the test leads quickly to the origin of the fault

### CODE REVIEW

**Comment by robertoschwald** [comment]
Hope this work is finished asap and leads to packages in https://download.bareos.org/bareos/contrib/.
The current contrib repo packages do not support Bareos 20, so I need to manually overwrite the mysql python files.

**Comment by joergsteffens** [comment]
This PR depends on improving the Bareos Python packaging, which is handled as separate task. As soon, as this is fixed, work on this PR can continue.

**Comment by pstorz** [comment]
Ups deleted accidentially, please reopen

**Review by sduehr — CHANGES_REQUESTED** [review]
Thanks a lot, only some small suggested changes below.
Additionally, in `docs/manuals/source/Appendix/Howtos/BackupOfThirdPartyDatabases.rst.inc` please replace `_mysqlbackups_` by `@mysqlbackup@`

**Comment by joergsteffens** [comment]
> Additionally, in `docs/manuals/source/Appendix/Howtos/BackupOfThirdPartyDatabases.rst.inc` please replace `_mysqlbackups_` by `@mysqlbackup@`

Done.

**Review by sduehr — APPROVED** [review]
Looks good now, thanks a lot!

**Pull request merged**
