### PR TITLE
Add missing newline to job message for TLS handshake.

### PR DESCRIPTION
**Pull request by rainerjung**
Add missing newline to job message for TLS handshake. 
This PR will fix the missing new line in job log as seen like
```
07-Jul 23:00 bareos-dir JobId 15390:  Handshake: Immediate TLS 07-Jul 23:00 bareos-dir JobId 15391:  Handshake: Immediate TLS 07-Jul 23:00 bareos-bie JobId 15390:  Encryption: PSK-AES256-CBC-SHA TLSv1/SSLv3
```
instead expected result
```
07-Jul 23:00 bareos-bie JobId 15391:  Handshake: Immediate TLS 
07-Jul 23:00 bareos-bie JobId 15390:  Encryption: PSK-AES256-CBC-SHA TLSv1/SSLv3
```
- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)

##### General
- [x] PR name is meaningful
- [x] Purpose of the PR is understood
- [x] Separate commit for this PR in the CHANGELOG.md, PR number referenced is same
- [x] Commit descriptions are understandable and well formatted

##### Source code quality

- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR
- [x] `bareos-check-sources --since-merge` does not report any problems
- [x] `git status` should not report modifications in the source tree after building and testing

### CODE REVIEW

**Comment by bruno-at-bareos** [comment]
Nice, maybe also time then to fix line 208 by removing the \n and adding also add_newline_in_joblog = true;

**Comment by bruno-at-bareos** [comment]
@rainerjung are you interested to do the whole PR process? It would be nice to have also your Name in AUTHORS file.

**Comment by rainerjung** [comment]
I am not sure, whether I currently can find the time to do the non-release build and test it. So if you can proceed without strong involvement from my side, that would be great. I do not really care whether you include me in the AUTHORS or not, because it is a trivial change. But if you like so, you can add "Rainer Jung". Of course, if you need to discuss something technical about the patch, I am here to answer as far as I can.
Thank you!

**Comment by bruno-at-bareos** [comment]
The PR will fix the missing new line in job log as seen like

**Review by pstorz — APPROVED** [review]
Good work!

**Pull request merged**
