### PR TITLE
catreq.cc: suppress missing batch con warning

### PR DESCRIPTION
**Pull request by pstorz**
When the Update_filelist command is received, the code issued a warning though this is not required.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Required backport PRs have been created

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

### CODE REVIEW

**Comment by bruno-at-bareos** [comment]
Looks good in first review, but I would really like to understand why I'm seeing this in joblog
```
26-Oct 13:32 bareos-sd JobId 3: Doing timed backup checkpoint. Next checkpoint in 3 seconds
26-Oct 13:32 bareos-dir JobId 3: Insert of attributes batch table with 1 entries start
26-Oct 13:32 bareos-dir JobId 3: Insert of attributes batch table done
...
26-Oct 13:32 bareos-sd JobId 3: stored/checkpoint_handler.cc:75 Volume changed, doing checkpoint:
26-Oct 13:32 bareos-dir JobId 3: Insert of attributes batch table with 1 entries start
26-Oct 13:32 bareos-dir JobId 3: Insert of attributes batch table done
```

**Review by sebsura — COMMENTED** [review]
If we do not want a job message, we should leave at least a debug message.

**Comment by bruno-at-bareos** [comment]
@sebsura 
> If we do not want a job message, we should leave at least a debug message.

Why we would like this debug as no action is simply required.
If we go a debug message, we should have one that say operation done.

**Review by bruno-at-bareos — APPROVED** [review]
I'm fine with the changes, Approved.

**Review by arogge — APPROVED** [review]

**Pull request merged**
